// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqRs8DABExd1LWutMarA8sYWnpxyKRCYc',
    appId: '1:578010305596:web:9ce855b192b23ad0d25f39',
    messagingSenderId: '578010305596',
    projectId: 'neurotribo-1bd8e',
    authDomain: 'neurotribo-1bd8e.firebaseapp.com',
    storageBucket: 'neurotribo-1bd8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdW67tVz7l9lcx3VzVDdRSVB76iYNyjv0',
    appId: '1:578010305596:android:6fb20c1cb0d0158dd25f39',
    messagingSenderId: '578010305596',
    projectId: 'neurotribo-1bd8e',
    storageBucket: 'neurotribo-1bd8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQVglCc9yzGZPeq9uyto_lNkmHsf3tUKs',
    appId: '1:578010305596:ios:90602e18a6de0f28d25f39',
    messagingSenderId: '578010305596',
    projectId: 'neurotribo-1bd8e',
    storageBucket: 'neurotribo-1bd8e.firebasestorage.app',
    iosBundleId: 'com.example.neuroTribo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQVglCc9yzGZPeq9uyto_lNkmHsf3tUKs',
    appId: '1:578010305596:ios:90602e18a6de0f28d25f39',
    messagingSenderId: '578010305596',
    projectId: 'neurotribo-1bd8e',
    storageBucket: 'neurotribo-1bd8e.firebasestorage.app',
    iosBundleId: 'com.example.neuroTribo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqRs8DABExd1LWutMarA8sYWnpxyKRCYc',
    appId: '1:578010305596:web:23fb543adc6b168ed25f39',
    messagingSenderId: '578010305596',
    projectId: 'neurotribo-1bd8e',
    authDomain: 'neurotribo-1bd8e.firebaseapp.com',
    storageBucket: 'neurotribo-1bd8e.firebasestorage.app',
  );
}
